/* SPDX-FileCopyrightText: 2011-2026 Matúš Sulír, Peter Jakubčo
   SPDX-License-Identifier: GPL-3.0-or-later */

import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.SourcesJar
import com.vanniktech.maven.publish.DeploymentValidation

plugins {
  id 'java-library'
  id 'com.intershop.gradle.javacc' version '6.1.0'
  id "com.vanniktech.maven.publish" version "0.36.0"
}

group = 'net.emustudio'
description = 'Emulator Disassembler Generator'
version = '1.6.0-SNAPSHOT'

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'net.emustudio:emulib:12.1.0-SNAPSHOT'
}

javacc {
  configs {
    template {
      inputFile = file('src/main/javacc/Grammar.jj')
      packageName = 'net.emustudio.edigen.parser'
    }
  }
}

mavenPublishing {
  coordinates("net.emustudio", "edigen", version)
  configure(new JavaLibrary(
          new JavadocJar.Javadoc(),
          new SourcesJar.Sources()
  ))

  signAllPublications()
  publishToMavenCentral(true, DeploymentValidation.PUBLISHED)

  pom {
    name = 'edigen'
    description = 'Emulator Disassembler Generator'
    url = 'https://github.com/emustudio/edigen'
    licenses {
      license {
        name = 'GNU General Public License, Version 2.0'
        url = 'https://www.gnu.org/licenses/gpl-2.0.txt'
      }
    }
    developers {
      developer {
        id = 'sulir'
        name = 'Matúš Sulír'
        url = 'https://github.com/sulir/'
      }
      developer {
        id = 'vbmacher'
        name = 'Peter Jakubčo'
        url = 'https://github.com/vbmacher'
      }
    }
    scm {
      connection = 'scm:git:git://github.com/emustudio/edigen.git'
      developerConnection = 'scm:git:ssh://github.com:emustudio/edigen.git'
      url = 'https://github.com/emustudio/edigen'
    }
  }
}

tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
  options.release = 11
  options.compilerArgs += ['-Xlint:-dep-ann']
}

signing {
  required {
    project.gradle.taskGraph.hasTask("publish")
  }

  def signingKey = findProperty("GPG_KEY") ?: System.getenv("GPG_KEY")
  def signingPassword = findProperty("GPG_PASSWORD") ?: System.getenv("GPG_PASSWORD")
  useInMemoryPgpKeys(signingKey, signingPassword)
}

test {
  doFirst {
    systemProperty 'edigen.test.classpath', classpath.asPath
  }
}

javadoc {
  exclude 'net/emustudio/edigen/parser/**'
  if (JavaVersion.current().isJava9Compatible()) {
    options.addBooleanOption('html5', true)
  }
}

repositories {
  mavenLocal()
  maven {
    name = 'Central Portal Snapshots'
    url = 'https://central.sonatype.com/repository/maven-snapshots/'

    content {
      includeModule("net.emustudio", "emulib")
      includeModule("net.emustudio", "edigen")
    }
  }
  mavenCentral()
}
